### ISSUE TITLE
If the directory does not exist, an exception is raised

### ISSUE THREAD

**Issue by dongzhaosheng73** [tekgator/GameLib.NET#18]
GameLib.Core   PathUtil.GetExecutables  If the directory does not exist, an exception is raised
`  public static List<string> GetExecutables(string path)
    {
        if (!Directory.Exists(path)) return new List<string>();
        return Directory.GetFiles(path, "*.exe", SearchOption.AllDirectories).ToList();
    }`

**Comment by tekgator** [comment]
Hi @dongzhaosheng73, thank you for the hint. Fixed in v1.3.3
